site_name: Token-based AuthN/Z for WLCG
site_description: Documentation on token-based AuthN/Z for WLCG

theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto mono
